import os
import sys
from sys import platform
Import('env')

build_dir = env['BUILDPATH']
program_name = build_dir + '/ECadTest.exe'
mfsolver_support = env['MFSOLVERSUPPORT']
boost_library_path = env['BOOSTLIBRARYPATH']
thirdpart_lib_path = env['THIRDPARTLIBPATH']

source_files = [
    'UnitTest.cpp'
]

libs_name = [
    'boost_serialization',
    'pthread',
    'png'
]

libs_path = [build_dir, boost_library_path, thirdpart_lib_path]

# boost_python
boost_python_support = env['BOOSTPYTHONSUPPORT']
if boost_python_support :
    boost_python_version = env['BOOSTPYTHONVERSION']
    boost_python_lib = 'boost_python' + str(int(boost_python_version * 10))
    libs_name.append(boost_python_lib)
    
# mfsolver
if mfsolver_support :
    mfsolver_path = env['MFSOLVERPATH']
    libs_path.append(mfsolver_path + '/mf2/lib')
    libs_path.append(mfsolver_path + '/mkl/lib')

    libs_name += [
        'mkl_intel_lp64',
        'mkl_sequential',
        'mkl_core',
        'ifcoremt',
        'imf',
        'iomp5',
        'irc',
        'intlc',
        'svml',
        'cublas',
        'cublasLt',
        'cudart',
        'ansmf',
        'ngcore'    
    ]   
rpath = libs_path
libs_name.append('Ecad')
env.Program(program_name,source_files,LIBS=libs_name,LIBPATH=libs_path, RPATH=rpath)