import os
import sys
from sys import platform
Import('env')

build_dir = env['BUILDPATH']
program_name = build_dir + '/ECadTest.exe'

source_files = [
    'UnitTest.cpp'
]

libs_name = [
    'Ecad',
    'boost_serialization',
    'pthread'
]

libs_path = [
    '/usr/local/lib',
]

libs_path.append(build_dir)

rpath = build_dir

if platform == "linux" or platform == "linux2" :
    libs_path.append('/usr/lib/x86_64-linux-gnu')
    libs_name.append('png')
elif platform == "darwin":
    libs_name.append('png')
#elif platform == "win32" :

env.Program(program_name,source_files,LIBS=libs_name,LIBPATH=libs_path, RPATH=rpath)