import os
import sys
from sys import platform
Import('env')

build_dir = env['BUILDPATH']
program_name = build_dir + '/ECadTest.exe'
mfsolver_support = env['MFSOLVERSUPPORT']
boost_library_path = env['BOOSTLIBRARYPATH']
thirdpart_lib_path = env['THIRDPARTLIBPATH']

source_files = [
    'UnitTest.cpp'
]

libs_name = [
    'boost_python36',
    'boost_serialization',
    'Ecad',
    'pthread',
    'png'
]

libs_path = [build_dir, boost_library_path, thirdpart_lib_path]

# mfsolver
if mfsolver_support :
    mfsolver_path = env['MFSOLVERPATH']
    libs_path.append(mfsolver_path + '/mf2/lib')
    libs_path.append(mfsolver_path + '/mkl/lib')

    libs_name += [
        'mkl_intel_lp64',
        'mkl_sequential',
        'mkl_core',
        'ifcoremt',
        'imf',
        'iomp5',
        'irc',
        'intlc',
        'svml',
        'cublas',
        'cublasLt',
        'cudart',
        'ansmf',
        'ngcore'    
    ]   

rpath = libs_path
env.Program(program_name,source_files,LIBS=libs_name,LIBPATH=libs_path, RPATH=rpath)