Import('env')
import os
import sys
from sys import platform

build_dir = env['BUILDPATH']
lib_name= build_dir + '/Ecad'

#Source to generate lib
source_files = [
    'extension/dmcdom/ECadExtDmcDomHandler.cpp',
    'extension/gds/ECadExtGdsHandler.cpp',
    'extension/gds/EGdsFileIO.cpp',
    'extension/gds/EGdsParser.cpp',
    'extension/ECadExtension.cpp',
    'simulation/ELayerStackMeshGeneration.cpp',
    'simulation/EMetalFractionMapping.cpp',
    'simulation/EThermalNetworkExtraction.cpp',
    'utility/EBoundaryCalculator.cpp',
    'utility/EFlattenUtility.cpp',
    'utility/ELayoutMergeUtility.cpp',
    'utility/ELayoutConnectivity.cpp',
    'ECell.cpp',
    'ECellCollection.cpp',
    'ECellInst.cpp',
    'ECellInstCollection.cpp',
    'ECollection.cpp',
    'ECollectionCollection.cpp',
    'EConnObj.cpp',
    'EConnObjCollection.cpp',
    'EDatabase.cpp',
    'EDataMgr.cpp',
    'EDefinition.cpp',
    'EDefinitionCollection.cpp',
    'EHierarchyObj.cpp',
    'EHierarchyObjCollection.cpp',
    'ELayer.cpp',
    'ELayerCollection.cpp',
    'ELayerMap.cpp',
    'ELayerMapCollection.cpp',
    'ELayoutView.cpp',
    'EMaterialDef.cpp',
    'ENet.cpp',
    'ENetCollection.cpp',
    'EObject.cpp',
    'EPadstackDef.cpp',
    'EPadstackDefCollection.cpp',
    'EPadstackDefData.cpp',
    'EPadstackInst.cpp',
    'EPadstackInstCollection.cpp',
    'EPrimitive.cpp',
    'EPrimitiveCollection.cpp',
    'EShape.cpp'
]

libs_name = [
    'boost_serialization'
]

libs_path = [
    '/usr/local/lib',
]

# mfsolver
mfsolver_support = env['MFSOLVERSUPPORT']
if mfsolver_support :
    mfsolver_path = env['MFSOLVERPATH']
    libs_path.append(mfsolver_path + '/mf2/lib')
    libs_path.append(mfsolver_path + '/mkl/lib')

    libs_name += [
        'mkl_intel_lp64',
        'mkl_sequential',
        'mkl_core',
        'ifcoremt',
        'imf',
        'iomp5',
        'irc',
        'intlc',
        'svml',
        'cublas',
        'cublasLt',
        'cudart',
        'ansmf',
        'ngcore'    
    ]   


if platform == "linux" or platform == "linux2" :
    libs_path.append('/usr/lib/x86_64-linux-gnu')
    libs_name.append('png')
    # libs_name.append('omp')
    libs_name.append('iomp5')
elif platform == "darwin":
    libs_name.append('png')

#Build lib
env.SharedLibrary(lib_name, source_files, LIBS=libs_name,LIBPATH=libs_path)
