name: linux
run-name: ecad test
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'
    
      - name: Install dependency
        run: sudo apt-get update && sudo apt-get install build-essential cmake ninja-build libeigen3-dev libpng-dev

      - name: Install boost library
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
            boost_version: 1.83.0
            platform_version: 22.04
            boost_install_dir: /home/runner/boost_1_83_0
      - name: check boost library
        run: ls -al /home/runner/boost_1_83_0/boost/boost/lib

      - name: Build ecad
        run: export BOOST_PATH=/home/runner/boost_1_83_0/boost/boost && cmake -Bbuild.release -G Ninja && cmake --build build.release

      - name: Run unit test
        run: build.release/bin/EcadTest.exe
        
      - name: Run examples
        run: build.release/bin/setup_design.exe

      - name: Run PyEcad Test
        run: python py/PyEcadTest.py
