name: Promote
run-name: Promote
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'
    
      - name: Install dependency
        run: sudo apt-get update && sudo apt-get -y install build-essential cmake ninja-build libeigen3-dev libpng-dev libjemalloc-dev

      - name: Install boost library
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
            boost_version: 1.83.0
            platform_version: 22.04
            boost_install_dir: /home/runner/boost_1_83_0
      
      - name: Check boost library
        run: ls -al /home/runner/boost_1_83_0/boost/boost/lib

      - name: Build ecad
        run: export BOOST_PATH=/home/runner/boost_1_83_0/boost/boost && cmake -Bbuild.release -DECAD_MALLOC_LIB=jemalloc -DENABLE_ASSERTION=ON -DENABLE_EXCEPTION=ON -DENABLE_ASAN=ON -DBUILD_PYECAD=OFF -G Ninja && cmake --build build.release

      - name: Run unit test
        run: build.release/bin/EcadTest.exe
        
      - name: Run cxx example - WolfSpeed SetupDesign
        run: build.release/bin/WolfSpeed_SetupDesign.exe

      - name: Run cxx example - WolfSpeed Static Thermal
        run: build.release/bin/WolfSpeed_StaticThermal.exe

      - name: Run cxx example - KiCAD Jetson Nano
        run: build.release/bin/KiCAD_JetsonNano.exe

      - name: Build PyEcad
        run: rm -rf build.release && cmake -Bbuild.release -DENABLE_ASSERTION=ON -DENABLE_EXCEPTION=ON -DBUILD_PYECAD=ON -DBUILD_ECAD_TEST=OFF -DBUILD_ECAD_EXAMPLES=OFF -G Ninja && cmake --build build.release

      - name: Run python example - WolfSpeed Setup Design
        run: python examples/python/wolfspeed/SetupDesign.py
    
      - name: Run python example - WolfSpeed Static Thermal
        run: python examples/python/wolfspeed/StaticThermal.py

      - name: Create pull request
        if: success()
        run: gh pr create -B master -H dev --title 'Merge dev into master' --body 'created by github action'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}